### ISSUE TITLE
Current user is not visible on Rails 6.0.0.rc1 with trestle-active_storage

### ISSUE THREAD

**Issue by brateq** [TrestleAdmin/trestle-auth#19]
Error:

```
ActionView::Template::Error (undefined local variable or method `current_user' for #<#<Class:0x00007fefef81aa60>:0x00007fefef03bb50>
Did you mean?  current_page?):
    14: 
    15:     <tbody>
    16:       <% collection.each do |instance| %>
    17:         <%= table.row.render(instance) %>
    18:       <% end %>
    19:     </tbody>
    20:   <% end %>
```

Ruby 2.6.2
Gems:
- rails 6.0.0rc1
- trestle 0.8.12
- trestle-auth 0.2.5
- trestle-active_storage 2.1.1

Steps to reproduce:
```
rails new trestle-auth-bug -T
gem 'trestle'
gem 'trestle-auth'

bundle 

rails generate trestle:install
rails generate trestle:auth:install
rails active_storage:install
rails db:create db:migrate db:seed 

# rails c
Administrator.create(email: "admin@example.com", password: "password", first_name: "Admin", last_name: "User")
```
This is working fine to this point
```
gem 'trestle-active_storage'

bundle
```

This code is working fine on Rails 5.2.3.

**Comment by spohlenz** [comment]
Thank you for reporting. This should now be fixed in TrestleAdmin/trestle@e0fa6dd3a5e46c6bcfbc37659b534b636426cf95.

I'll likely put out a new gem release early this week.
